"""Minimal immutable input profile."""

CANONICAL_TIMEZONE = "Asia/Singapore"

EDITORIAL_WEIGHTS = {
    "opening_hook_potential": 20,
    "curiosity_gap": 20,
    "emotional_stakes": 15,
    "escalation_potential": 10,
    "payoff_quality": 10,
    "title_potential": 10,
    "broad_relatability": 5,
    "originality": 5,
    "narration_suitability": 5,
}

TITLE_WEIGHTS = {
    "curiosity_gap": 30,
    "emotional_impact": 20,
    "unanswered_question": 15,
    "immediate_comprehension": 10,
    "specificity": 10,
    "natural_phrasing": 5,
    "conciseness": 5,
    "truthful_reflection": 5,
}

CATEGORIES = {
    "RELATIONSHIP", "DATING", "MARRIAGE", "BETRAYAL", "FAMILY", "INHERITANCE",
    "MONEY", "WORKPLACE", "REVENGE", "FRIENDSHIP", "WEDDING", "ENTITLED_PERSON",
    "NEIGHBOR", "SECRETS", "DISCOVERY", "SOCIAL_CONFLICT", "PROPERTY", "PARENTING",
    "MORAL_DILEMMA", "KINDNESS", "MISUNDERSTANDING", "HIDDEN_IDENTITY", "CONSEQUENCES",
    "TWIST", "WILDCARD",
}

EMOTIONS = {
    "ANGER", "BETRAYAL", "INJUSTICE", "EMBARRASSMENT", "FEAR", "DISBELIEF", "REVENGE",
    "LOVE", "GUILT", "REGRET", "SURPRISE", "RELIEF", "HOPE", "SADNESS", "JOY",
}

OPENING_STYLES = {
    "IMMEDIATE_REVELATION", "CONTRADICTION", "DISCOVERY", "CONSEQUENCE_FIRST",
    "URGENT_CONFLICT", "SHOCKING_STATEMENT", "UNANSWERED_EVENT", "DECISION_FIRST",
}

TITLE_STYLES = {
    "HIDDEN_REVELATION", "DISCOVERY", "NORMAL_TO_ABNORMAL", "DECISION_CONSEQUENCE",
    "COUNTDOWN", "UNDERESTIMATED_NARRATOR", "MORAL_CONFLICT", "DELAYED_REVELATION",
    "CONTRADICTION", "CONSEQUENCE_FIRST",
}

ENDING_STYLES = {
    "REVERSAL", "BACKFIRE", "REVEAL", "CONSEQUENCE", "RECONCILIATION", "BOUNDARY_SET",
    "JUSTICE", "SACRIFICE", "KINDNESS_RETURNED", "BITTERSWEET", "OPEN_RESOLUTION",
}

PROTAGONIST_ROLES = {
    "PARTNER", "SPOUSE", "EMPLOYEE", "MANAGER", "SIBLING", "PARENT", "ADULT_CHILD",
    "FRIEND", "ROOMMATE", "NEIGHBOR", "TENANT", "LANDLORD", "CUSTOMER", "OWNER",
    "BRIDE", "GROOM", "STUDENT", "TEACHER", "TRAVELER", "STRANGER", "RELATIVE",
}

ANTAGONIST_ROLES = PROTAGONIST_ROLES | {"COWORKER", "BOSS", "EX_PARTNER", "VENDOR", "GUEST"}
